### ISSUE TITLE
Editable ParsedText

### ISSUE THREAD

**Issue by Addictorator** [fayeed/flutter_parsed_text#10]
Is it possible to make ParsedText optionally editable, like with a boolean? I understand RichText doesn't allow for it, since there's preset spans with fixed portions of texts and textstyles, but it makes sense conceptually for parsed text, where the spans are built by matching the text, thus in a case of the text being edited, simply reparse it with the changes. 

Programmatically, might be difficult to implement though. Is this a possible feature or would it require too much of an overhaul? Thanks either way!

**Comment by fayeed** [comment]
In the previous implementation for this package, I actually didn't use `RichText` since I didn't know about it so I used a `Row` to implement it and then later I changed it to `RichText` as it seems like a better solution. 

To answer your question is possible or not? Yes, it is but not with `RichText`, it would have been possible in the previous implementation.
