### ISSUE TITLE
Phone number regex can be improved

### ISSUE THREAD

**Issue by erickjtorres** [fayeed/flutter_parsed_text#2]
The regular expression used for phone numbers does not take into account escape characters that might come before the phone number. Also if a user wants to input an extension sthe regex won't work but that is less of a concern.

**Comment by fayeed** [comment]
@erickjtorres can you give an example of what you are doing because it works fine for most of the phone number format that I tried.

**Comment by erickjtorres** [comment]
Currently at work we have data that is returned in the following format 
```
This app is offered by [Company]\n302, Woodcliff Lake, New Jersey 02277-7731\nAttn: Customer Relations, Services.\n\nContact:\nCustomer.relations@generic.com\n+1 (800) 831-1117
```
The +1 gets cut off from the regular expression. This could be because of how currently the text is split into spaces. The scope of the regular expression is narrowed to that word. 

I also noticed that because of the above this also means that something like (800) 831-1117-213 3213212131321 will be considered a  phone number.

**Comment by fayeed** [comment]
ok, I think this regex would work great `^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$`

**Comment by erickjtorres** [comment]
The above still does not seem to work and further restricts it to using dashes because of the scoping of the word. I'll try to play around with it a bit and perhaps come up with a proposed solution.

**Comment by fayeed** [comment]
My bad so it not so much about the regex as it is about how the library works so it splits the string by space and then performs regex validation on the individual word so in your case `+1 (800) 831-1117` this gets split into 3 parts `+1` `(800)` `831-1117` hence the phone regex doesn't work and also it doesn't split at `\n` so that doesn't work either.

I have changed a few things in the package and it should work now, do update it to version `1.2.0`

Here's the text that I parsed:

`"[@michael:51515151] Hello this is an example of the ParsedText, links like http://www.google.com or http://www.facebook.com are clickable and phone number 444-555-6666 can call too. But you can also do more with this package, for example, Bob will change style and David too.\nAlso a US number example +1-(800)-831-1117. foo@gmail.com And the magic number is 42! #flutter #flutterdev"`


![Webp net-resizeimage](https://user-images.githubusercontent.com/8464270/62611767-d892bd00-b923-11e9-8f0b-e6953ebffb30.png)

**Comment by erickjtorres** [comment]
Thats what I meant sorry for not explaining well. But it looks like it works well now! And the solution you have for it is great. Thanks for looking into the issue!
