### ISSUE TITLE
takes the number in url as phone no

### ISSUE THREAD

**Issue by joselyn9** [fayeed/flutter_parsed_text#5]
Hi
if there is a number in the url 
e.g.
https://apps.apple.com/id/app/facebook/id284882215

it considers the trailing no as phone number.

Please check
TIA

**Comment by fayeed** [comment]
@joselyn9 It's due to how the code works first it checks if there are any matches for an email in the text parameter, second phone and then URL and at last custom pattern that you provide so since the "284882215" matches first it gets parsed as a phone. The simplest solution to this implement your `regex` pattern that should resolve your problem.
